#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml
api_login_check:
    path: /api/login_check
swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
# security open api bearer token for api/users for get

